name: Release

on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io

jobs:
  release-assets:
    name: Github Release Assets
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Upload Assets
        run: make upload-github-release-assets
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAGGED_VERSION: ${{ github.event.release.tag_name }}

  push-builder-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_TOKEN }}
      - name: Push Docker Container
        run: make docker-push
        env:
          TAGGED_VERSION: ${{ github.event.release.tag_name }}

  push-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_TOKEN }}
      - name: Push images
        run: make docker-push-bee docker-push-operator
        env:
          TAGGED_VERSION: ${{ github.event.release.tag_name }}

  push-example-programs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_TOKEN }}

      - name: Build builder container
        run: make docker-build
        env:
          TAGGED_VERSION: ${{ github.event.release.tag_name }}

      - name: Build CLI
        run: make bee-linux-amd64
        env:
          TAGGED_VERSION: ${{ github.event.release.tag_name }}

      - name: Push example images
        run: make release-examples -B
        env:
          TAGGED_VERSION: ${{ github.event.release.tag_name }}

  release-helm-charts:
    name: Release Helm Charts
    needs: validate-release-version
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Setup Private Repo Permissions
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global url."https://${TOKEN}@github.com/solo-io/".insteadOf "https://github.com/solo-io/"
      - name: Install Protoc
        uses: arduino/setup-protoc@922bd7afadc612c340f111d009371fccf38306ff
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: google-github-actions/setup-gcloud@a48b55b3b0eeaf77b6e1384aab737fbefe2085ac
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
        name: Gcloud Login
      - name: Publish Helm
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAGGED_VERSION: ${{ github.event.release.tag_name }}
        run: |
          make install-go-tools release-helm